usr/lib/*/libhybris-eglplatformcommon.so.*
usr/lib/*/libhybris-hwcomposerwindow.so.*
usr/lib/*/libsync.so.*
usr/lib/*/libui.so.*
usr/lib/*/libsf.so.*
usr/lib/*/libis.so.*
usr/lib/*/libcamera.so.*
usr/lib/*/libwifi.so.*
usr/lib/*/libnfc_nxp.so.*
usr/lib/*/libvibrator.so.*
usr/lib/*/libhybris/*.so
usr/lib/*/libwayland-egl.so.*		usr/lib/aarch64-linux-gnu/libhybris-egl
usr/lib/*/libEGL.so.*		usr/lib/aarch64-linux-gnu/libhybris-egl
usr/lib/*/libGLESv2.so.*	usr/lib/aarch64-linux-gnu/libhybris-egl
usr/lib/*/libGLESv1_CM.so.*	usr/lib/aarch64-linux-gnu/libhybris-egl
usr/lib/*/libOpenCL.so.*	usr/lib/aarch64-linux-gnu/libhybris-egl